### PR TITLE
feature: support ZodCustom and ZodEffect (refine/transfrom/...)

### PR DESCRIPTION
**Pull request by Danielduel**
I like to brand types like api keys or access tokens in projects that integrate many APIs or with APIs that have multiple tiers of access based on eachother.
So for example I get typeguard firing a red underline under a call to user-protected endpoint with bot account access token instead of figuring what went wrong during runtime.

### CODE REVIEW

**Comment by oliver-oloughlin** [comment]
Hi, thanks for taking the time to submit this PR. Good catch with the insufficient Zod types there. I think the tests are just failing because of type issues. I'll take a look, it's been a while since I updated this project.

It might be worth mentioning that I have primarily moved over to working on [jex](https://github.com/oliver-oloughlin/jex), as a simplified, more modular and general purpose alternative to `zod_api`. I'm also not sure if I have access to the publishing account for this project on NPM anymore sadly.

I took your tests and modified the code a bit to adapt to `jex`, and seems they are passing fine. So if you are interested, I would recommend swapping out `zpd_api` for `jex`, as it doesn't suffer from the same issues as you pointed out here. Modified code below:

```ts
import { z } from "zod"
import { type Brand, make } from "https://deno.land/x/ts_brand@0.0.1/mod.ts"
import { jex } from "./mod.ts"
import { assertType, type IsExact } from "jsr:@std/testing/types"

// This example bases on usecase that I couldn't use custom+transforms in
// In real-world scenario there's another layer that adds `Bearer ...` and brands it as a header value, I've skipped it here
// Current version doesn't offer typeguards for transform (not sure how to approach it), custom is handled automagically
// It allows you to use your current typeguarded schemas without typeerrors

type UserToken = Brand<string, "UserToken">
const makeUserToken = (userToken: string) => make<UserToken>()(userToken)
const userTokenSchema = z.string().transform(makeUserToken)
const userAuthHeaderSchema = z.object({
  Authorization: userTokenSchema,
})
const userTokenSchema2 = z
  .custom<UserToken>((x) => typeof x === "string")
  .transform(makeUserToken)
const userAuthHeaderSchema_USING_CUSTOM = z.object({
  Authorization: userTokenSchema2,
})

type AppToken = Brand<string, "AppToken">
const makeAppToken = (appToken: string) => make<AppToken>()(appToken)
const appTokenSchema = z.string().transform(makeAppToken)
const appAuthHeaderSchema = z.object({
  Authorization: appTokenSchema,
})

// Let's pretend this API just takes Authorization as every option and responds with Authorization
const api = jex({
  fetcher: () => Promise.resolve(new Response("mock")),
  baseUrl: "test",
  endpoints: {
    "/user/header/echo": {
      get: {
        data: userAuthHeaderSchema,
        headers: userAuthHeaderSchema,
        query: userAuthHeaderSchema,
      },
      post: {
        data: userAuthHeaderSchema,
        headers: userAuthHeaderSchema,
        body: userAuthHeaderSchema,
        query: userAuthHeaderSchema,
      },
      delete: {
        body: userAuthHeaderSchema_USING_CUSTOM,
        data: userAuthHeaderSchema_USING_CUSTOM,
        headers: userAuthHeaderSchema_USING_CUSTOM,
        query: userAuthHeaderSchema_USING_CUSTOM,
      },
      options: {
        body: userAuthHeaderSchema,
        data: userAuthHeaderSchema,
        headers: userAuthHeaderSchema,
        query: userAuthHeaderSchema,
      },
      patch: {
        body: userAuthHeaderSchema,
        data: userAuthHeaderSchema,
        headers: userAuthHeaderSchema,
        query: userAuthHeaderSchema,
      },
      put: {
        body: userAuthHeaderSchema,
        data: userAuthHeaderSchema,
        headers: userAuthHeaderSchema,
        query: userAuthHeaderSchema,
      },
    },
    "/app/header/echo": {
      get: {
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
      post: {
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        body: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
      delete: {
        body: appAuthHeaderSchema,
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
      options: {
        body: appAuthHeaderSchema,
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
      patch: {
        body: appAuthHeaderSchema,
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
      put: {
        body: appAuthHeaderSchema,
        data: appAuthHeaderSchema,
        headers: appAuthHeaderSchema,
        query: appAuthHeaderSchema,
      },
    },
  },
})

const appToken = makeAppToken("appToken")
const userToken = makeUserToken("userToken")

Deno.test("Call with branding types", async () => {
  const a = await api["/user/header/echo"].delete({
    body: { Authorization: userToken },
    headers: { Authorization: userToken },
    query: { Authorization: userToken },
  })

  assertType<
    IsExact<
      typeof a.data,
      {
        Authorization: UserToken
      } | null
    >
  >(true)
})

Deno.test("Expect type error when using incorrect branded type", () => {
  // dryrun, test will fail to build if it ever doesn't produce an error
  api["/user/header/echo"].delete({
    // @ts-expect-error this should be userToken, appToken should be catched by typeguard
    body: { Authorization: appToken },
    // @ts-expect-error this should be userToken, appToken should be catched by typeguard
    headers: { Authorization: appToken },
    // @ts-expect-error this should be userToken, appToken should be catched by typeguard
    query: { Authorization: appToken },
  })
})

Deno.test("Expect type error when not using brands when brands are required", () => {
  // dryrun, test will fail to build if it ever doesn't produce an error
  api["/user/header/echo"].delete({
    // @ts-expect-error this should be userToken, string should be catched by typeguard
    body: { Authorization: "Bearer something" },
    // @ts-expect-error this should be userToken, string should be catched by typeguard
    headers: { Authorization: "Bearer something" },
    // @ts-expect-error this should be userToken, string should be catched by typeguard
    query: { Authorization: "Bearer something" },
  })
})

Deno.test("Typecheck custom", () => {
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["delete"]
      >[0]["body"]["Authorization"],
      UserToken
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["delete"]
      >[0]["headers"]["Authorization"],
      UserToken
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["delete"]
      >[0]["query"]["Authorization"],
      UserToken
    >
  >(true)
})

Deno.test("Typecheck transfrom", () => {
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["options"]
      >[0]["body"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["options"]
      >[0]["headers"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["options"]
      >[0]["query"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["patch"]
      >[0]["body"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["patch"]
      >[0]["headers"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["patch"]
      >[0]["query"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["post"]
      >[0]["body"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["post"]
      >[0]["headers"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["post"]
      >[0]["query"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["put"]
      >[0]["body"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["put"]
      >[0]["headers"]["Authorization"],
      string
    >
  >(true)
  assertType<
    IsExact<
      Parameters<
        typeof api["/user/header/echo"]["put"]
      >[0]["query"]["Authorization"],
      string
    >
  >(true)
})
```

**Comment by oliver-oloughlin** [comment]
I fixed the type import issues and updated main. If you merge those changes in I think the PR can be merged :)

**Comment by Danielduel** [comment]
I've rebased this branch on current main.
The only place that is necessary for me being updated is the `deno/x` - and I think it will automagically handle this if you don't have anything custom set for this package.
From what I can see `jex` will cover my usecases and will be easy to port to.
I prefer to migrate to jex after finishing current milestone, so I would like `zod_api` be updated either way.
I suggest putting a notice on the top of README that you suggest using `jex` instead of `zod_api`.

**Comment by oliver-oloughlin** [comment]
I moved `zod_api` over to JSR a while back, I hope that works for you. I created a new release and added a comment in the README as you suggested, good point.

**Pull request merged**
